spring:
  application:
    name: DockerFirst

#  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

server:
    port: ${SERVER_PORT:8080}

app:
  file:
    path: ./names.txt